name: Report Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Java distribution
          java-version: '17'       # Replace with your Java version

      - name: Build with Maven
        run: mvn install -DskipTests

      - name: Run tests and generate report
        run: |
          mvn test > test-report.txt || true  # Run tests and save output to test-report.txt
        continue-on-error: true  # Continue even if tests fail

      - name: Upload test report as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test-report.txt

      - name: Notify via webhook (optional)
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"Java test report available.\"}" https://your-webhook-url
