name: Selenium Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    services:
      # Set up a service to run a Selenium server
      selenium:
        image: selenium/standalone-chrome:latest  # Use the latest Chrome image
        ports:
          - 4444:4444
        options:
          --shm-size 2g  # Increase shared memory for better performance

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Java distribution
          java-version: '17'       # Java version, change as needed

      - name: Build with Maven
        run: mvn clean compile       # Compile the project

      - name: Run Selenium Tests
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub  # URL to Selenium server
        run: mvn test -Dselenium.server.url=$SELENIUM_URL

      - name: Upload test report as an artifact
        uses: actions/upload-artifact@v3
        with:
           name: test-report
           path: .github/workflows/test-report.txt

      - name: Send Email
        if : ${{ always() }}
        uses: dawidd6/action-send-mail@v1.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_ADDRESS }}
          password: ${{ secrets.EMAIL_PASSWORD}}
          subject: Api report
          to: heba.emam@vodafone.com,hebaibrahim.emam@gmail.com #,aya.shafei@vodafone.com.eg,sally.sedky@vodafone.com.eg  access
          from: ${{ secrets.EMAIL_ADDRESS }}
          body: |
            <!DOCTYPE html>
            <html>
            <body>
              <h1>Test Report</h1>
              <p>Dear team,</p>
              <p>${{ github.actor }} just run action on repo ${{ github.repository }}</p>
              <p>Please find the attached test report.</p>
              <p>Best regards,<br>Your CI/CD System</p>
            </body>
            </html>
            content_type: text/html

